apiVersion: v1
kind: Service
metadata:
  name: {{ include "backup.fullname" . }}-proxy
  namespace: {{ include "backup.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "backup.labels.proxy" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
